### PR TITLE
gluon-config-mode-geo-location: add border

### PR DESCRIPTION
**Pull request by rubo77**
transition is nice, if you change the height of the map, it will change with ease

### CODE REVIEW

**Comment by 2tata** [comment]
It seems not possible, because if I handle the height on runtime, the map is not able to fully load anymore.

Anyway, you need to rebase your PR.

**Comment by rubo77** [comment]
i rebased it and wil try out after the weekend

**Comment by rubo77** [comment]
I checked again, the border works. I removed `transition:0.7s` because it was not possible to use a height change instead of display none and block change

**Comment by 2tata** [comment]
I have applyed the Border.

**Pull request closed without merging**
